version: '3'
name: tune-weaver
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_SCHEMA: tune-weaver
    ports:
      - '5432:5432'

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --bind 0.0.0.0

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
